//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrador
    {
        public int IDadmin { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public string estado { get; set; }
        public string tipo { get; set; }
    }
}
