//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alquiler
    {
        public Alquiler()
        {
            this.Contratos = new HashSet<Contrato>();
            this.Pagos_alquiler = new HashSet<Pago_alquiler>();
            this.Seguros = new HashSet<Seguro>();
        }
    
        public int nro_alquiler { get; set; }
        public int cod_unidad { get; set; }
        public int nro_inquilino { get; set; }
        public string estado { get; set; }
    
        public virtual Inquilino Inquilinos { get; set; }
        public virtual Unidad Unidades { get; set; }
        public virtual ICollection<Contrato> Contratos { get; set; }
        public virtual ICollection<Pago_alquiler> Pagos_alquiler { get; set; }
        public virtual ICollection<Seguro> Seguros { get; set; }
    }
}
