//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contrato
    {
        public Contrato()
        {
            this.Valores_mensuales = new HashSet<Valor_mensual>();
        }
    
        public int cod_contrato { get; set; }
        public int nro_alquiler { get; set; }
        public int cod_unidad { get; set; }
        public int nro_inquilino { get; set; }
        public Nullable<System.DateTime> fecha_realizacion { get; set; }
        public Nullable<System.DateTime> fecha_caducidad { get; set; }
        public string descripcion_unidad { get; set; }
        public string anexo { get; set; }
    
        public virtual Alquiler Alquileres { get; set; }
        public virtual ICollection<Valor_mensual> Valores_mensuales { get; set; }
    }
}
