//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contratista
    {
        public Contratista()
        {
            this.Mejoras = new HashSet<Mejora>();
            this.Reparaciones = new HashSet<Reparacion>();
        }
    
        public int cod_contratista { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string disponibilidad { get; set; }
    
        public virtual ICollection<Mejora> Mejoras { get; set; }
        public virtual ICollection<Reparacion> Reparaciones { get; set; }
    }
}
