//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta_corriente
    {
        public int nro_inquilino { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<double> saldo { get; set; }
    
        public virtual Inquilino Inquilinos { get; set; }
    }
}
