//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquilino
    {
        public Inquilino()
        {
            this.Alquileres = new HashSet<Alquiler>();
        }
    
        public int nro_inquilino { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string e_mail { get; set; }
        public string dni { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<Alquiler> Alquileres { get; set; }
        public virtual Cuenta_corriente Cuenta_corriente1 { get; set; }
    }
}
