//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mejora
    {
        public int cod_contratista { get; set; }
        public int nro_mejora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> valor { get; set; }
        public int cod_unidad { get; set; }
        public string observaciones { get; set; }
        public string detalles { get; set; }
    
        public virtual Contratista Contratistas { get; set; }
        public virtual Unidad Unidades { get; set; }
    }
}
