//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad
    {
        public Propiedad()
        {
            this.Unidades = new HashSet<Unidad>();
        }
    
        public int cod_propiedad { get; set; }
        public string ciudad { get; set; }
        public string direccion { get; set; }
        public Nullable<double> m2 { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<Unidad> Unidades { get; set; }
    }
}
