//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguro
    {
        public int cod_seguro { get; set; }
        public int nro_alquiler { get; set; }
        public int cod_unidad { get; set; }
        public int nro_inquilino { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public string aseguradora { get; set; }
        public string tipo_seguro { get; set; }
        public string descripcion { get; set; }
    
        public virtual Alquiler Alquileres { get; set; }
        public virtual Pago_seguro Pagos_seguro { get; set; }
    }
}
