//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unidad
    {
        public Unidad()
        {
            this.Alquileres = new HashSet<Alquiler>();
            this.Fotos = new HashSet<Foto>();
            this.Mejoras = new HashSet<Mejora>();
            this.Reparaciones = new HashSet<Reparacion>();
        }
    
        public int cod_unidad { get; set; }
        public int cod_propiedad { get; set; }
        public Nullable<double> m2 { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<Alquiler> Alquileres { get; set; }
        public virtual ICollection<Foto> Fotos { get; set; }
        public virtual ICollection<Mejora> Mejoras { get; set; }
        public virtual Propiedad Propiedades { get; set; }
        public virtual ICollection<Reparacion> Reparaciones { get; set; }
    }
}
